-- ═══════════════════════════════════════════════════════════════
-- SULSIGN OS 2.0 — NOVAS TABELAS (Almoxarifado + Diário de Obra)
-- Rodar no SQL Editor do Supabase (obeamqkcuytctfczhook)
-- Padrão: soft delete via deletado_em, RLS para authenticated.
-- ═══════════════════════════════════════════════════════════════

-- ── ALMOXARIFADO: ITENS ──
create table if not exists almoxarifado_itens (
  id          bigint generated by default as identity primary key,
  nome        text not null,
  categoria   text,                -- Madeira, Metalon, Tecido, Ferragem, Tinta, Elétrica, Outros
  unidade     text default 'un',   -- un, m, m², chapa, vara, kg, l
  qtd         numeric default 0,
  qtd_minima  numeric default 0,   -- alerta de reposição
  local       text,                -- prateleira/setor no galpão
  obs         text,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now(),
  deletado_em timestamptz
);

-- ── ALMOXARIFADO: MOVIMENTAÇÕES ──
create table if not exists almoxarifado_mov (
  id          bigint generated by default as identity primary key,
  item_id     bigint references almoxarifado_itens(id),
  tipo        text not null check (tipo in ('entrada','saida','ajuste')),
  qtd         numeric not null,
  job         text,                -- SS-YYYY_MM-NN quando saída para job
  responsavel text,                -- quem retirou/recebeu
  obs         text,
  created_at  timestamptz default now()
);

-- ── DIÁRIO DE OBRA ──
create table if not exists diario_obra (
  id          bigint generated by default as identity primary key,
  os_num      text,                -- vínculo com ordens_servico.num
  job         text,                -- SS-YYYY_MM-NN
  data        date not null default current_date,
  turno       text,                -- Manhã, Tarde, Noite, Madrugada
  equipe      text,                -- nomes separados por vírgula
  atividades  text not null,       -- o que foi feito
  ocorrencias text,                -- problemas, pendências, acidentes
  clima       text,                -- para montagens externas
  fotos_link  text,                -- link Drive da pasta de fotos do dia
  autor       text,                -- quem registrou
  created_at  timestamptz default now(),
  deletado_em timestamptz
);

-- ── ÍNDICES ──
create index if not exists idx_alm_mov_item on almoxarifado_mov(item_id);
create index if not exists idx_dob_os on diario_obra(os_num);
create index if not exists idx_dob_data on diario_obra(data desc);

-- ── RLS (mesmo padrão das tabelas existentes: authenticated total) ──
alter table almoxarifado_itens enable row level security;
alter table almoxarifado_mov  enable row level security;
alter table diario_obra       enable row level security;

drop policy if exists alm_itens_auth on almoxarifado_itens;
create policy alm_itens_auth on almoxarifado_itens
  for all to authenticated using (true) with check (true);

drop policy if exists alm_mov_auth on almoxarifado_mov;
create policy alm_mov_auth on almoxarifado_mov
  for all to authenticated using (true) with check (true);

drop policy if exists dob_auth on diario_obra;
create policy dob_auth on diario_obra
  for all to authenticated using (true) with check (true);

-- ── TRIGGER updated_at (almoxarifado_itens) ──
create or replace function ss20_touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_alm_itens_touch on almoxarifado_itens;
create trigger trg_alm_itens_touch
  before update on almoxarifado_itens
  for each row execute function ss20_touch_updated_at();
